# Generated by Django 4.0.5 on 2022-06-24 07:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='my_field',
        ),
        migrations.AddField(
            model_name='trip',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('01', 'Janauary'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('overnight', 'Overnight'), ('shopping', 'Shopping'), ('food included', 'Food Included'), ('excursion', 'Excursion'), ('for students', 'For Students'), ('holiday', 'Holiday')], max_length=30),
        ),
    ]
