# Generated by Django 4.0.5 on 2022-06-24 11:54

from django.db import migrations
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_my_field_trip_months_alter_trip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('overnight', 'Overnight'), ('shopping', 'Shopping'), ('food included', 'Food Included'), ('excursion', 'Excursion'), ('for students', 'For Students'), ('holiday', 'Holiday')], max_length=63),
        ),
        migrations.AlterField(
            model_name='trip',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
