# Generated by Django 4.0.5 on 2022-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_image_name_alter_trip_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(blank=True, to='trips.category', verbose_name='trip'),
        ),
    ]
