# Generated by Django 4.0.5 on 2022-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_category_remove_trip_category_trip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(blank=True, to='trips.category'),
        ),
    ]
