# Generated by Django 4.0.5 on 2022-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.CharField(default='1 нощувка', max_length=50),
        ),
    ]
