# Generated by Django 4.0.5 on 2022-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='months',
        ),
        migrations.AddField(
            model_name='trip',
            name='months',
            field=models.ManyToManyField(to='trips.month'),
        ),
    ]
