# Generated by Django 4.0.5 on 2022-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_month_remove_trip_months_trip_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/trip-images/'),
        ),
    ]
