# Generated by Django 4.0.5 on 2022-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_picture_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(to='trips.category'),
        ),
    ]
