# Generated by Django 4.0.5 on 2022-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_trip_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
