# Generated by Django 4.0.5 on 2022-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='document',
            field=models.FileField(default='opa.txt', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
