# Generated by Django 4.0.5 on 2022-06-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_condition_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimage',
            options={'verbose_name': 'Начален Екран - Снимка', 'verbose_name_plural': 'Начален Екран - Снимка'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Снимка', 'verbose_name_plural': 'Снимки'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Екскурзия/Почивка', 'verbose_name_plural': 'Екскурзии и Почивки'},
        ),
    ]
