# Generated by Django 4.0.5 on 2022-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_homeimage_options_alter_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Условия и Документи'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(),
        ),
    ]
