# Generated by Django 4.0.5 on 2022-07-01 10:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_condition_options_alter_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на вавеждане'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име на Документа'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='home_image',
            field=models.ImageField(upload_to='images/', verbose_name='Снимка на Началният Екран'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Име за снимката'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip', verbose_name='Екскурзия/Почивка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(to='trips.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Държава'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.CharField(default='1 нощувка', max_length=50, verbose_name='Пордължителнот'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='main_image',
            field=models.ImageField(upload_to='main_images/', verbose_name='Главна Снимка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='months',
            field=models.ManyToManyField(to='trips.month', verbose_name='През Месеци:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='top_offer',
            field=models.BooleanField(default=False, verbose_name='Топ Оферта'),
        ),
    ]
