# Generated by Django 4.0.5 on 2022-07-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_trip_created_at_alter_condition_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
    ]
